[project]
name = "tfg-leyre"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymupdf==1.23.8",
    "python-pptx>=0.6.23",
    "python-dotenv",
    "groq",
    "chromadb",
    "pydantic",
    "pytest",
    "fastapi",
    "uvicorn",
    "mcp[cli]",
    "wikipedia-api",
]
